In [1]:
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline

In [2]:
# 乱数を固定
np.random.seed(0)

# 0.0以上1.0未満の一様分布を生成
rand_list = np.random.rand(10)
rand_list

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [3]:
# 3行3列の行列
rand_list = np.random.rand(3, 3)
rand_list

array([[0.79172504, 0.52889492, 0.56804456],
       [0.92559664, 0.07103606, 0.0871293 ],
       [0.0202184 , 0.83261985, 0.77815675]])

In [4]:
# a以上b未満の範囲での乱数を取得したいとき
a = 2
b = 4

# a以上b未満で4行4列の一様分布乱数の要素を持つ行列
rand_list = (b - a) * np.random.rand(4, 4) + a
rand_list

array([[3.7400243 , 3.95723668, 3.59831713, 2.92295872],
       [3.56105835, 2.23654885, 3.27984204, 2.28670657],
       [3.88933783, 3.04369664, 2.82932388, 2.52911122],
       [3.54846738, 2.91230066, 3.1368679 , 2.0375796 ]])

In [5]:
# 横ベクトルの表し方
a = np.array([2, 1])
a

array([2, 1])

In [6]:
# 縦ベクトルの表し方
a = np.array([[1], [2]])
a

array([[1],
       [2]])

In [7]:
# 2×2の行列
a = np.array([[1, 2], [3, 4]])
print(a)

[[1 2]
 [3 4]]


In [8]:
a.T

array([[1, 3],
       [2, 4]])

In [9]:
# 内積の計算
b = np.array([1, 3])
c = np.array([4, 2])
print(b.dot(c))

10


In [10]:
# ベクトルの大きさ ノルムの計算
a = np.array([1, 3])
print(np.linalg.norm(a))

3.1622776601683795
